language: en
pipeline:
  - name: SpacyNLP
    model: "en_core_web_sm"
  - name: SpacyTokenizer
  - name: SpacyEntityExtractor
    dimensions: ["PERSON", "GPE", "PRODUCT", "LOC", "DATE", "ORDINAL", "MONEY"]
  - name: SpacyFeaturizer
    pooling: mean
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 2
  - name: DIETClassifier
    epochs: 300
    
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy